### ISSUE TITLE
LICENSE and copyright statement please (Open Source compliance)

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/go-connlimit#4]
The project needs a license and a copyright statement. Please add.

**Comment by avoidik** [comment]
thank you @banks, will you re-release v0.2.0 or it will be v0.2.1?

**Comment by onlyjob** [comment]
@avoidik, retrospective changing of releases is a very bad, universally condemned idea.
It can only ever be a new release. Read more about versioning at https://semver.org/

Thanks for adding LICENSE, @banks, but copyright statement is still missing.

**Comment by banks** [comment]
Thanks. Done!

**Comment by avoidik** [comment]
@onlyjob would you mind to suggest the way how to update dependents to backport this into their products retrospectively?

**Comment by onlyjob** [comment]
> would you mind to suggest the way how to update dependents to backport this into their products retrospectively into existing versions?

@avoidik, I don't understand the problem that you are aiming to solve. You can backport changes with patch but documentation changes such as licensing/copyright information hardly warrant the effort. Perhaps you could mention (URLs of) the relevant files in your license documentation?
